import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const TURING_EXPERIMENTAL = truthy("TURING_EXPERIMENTAL")
const TURING_DISABLE_CLAUDE_CODE = truthy("TURING_DISABLE_CLAUDE_CODE")
const TURING_DISABLE_CLAUDE_CODE_SKILLS =
  TURING_DISABLE_CLAUDE_CODE || truthy("TURING_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["TURING_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  TURING_AUTO_HEAP_SNAPSHOT: truthy("TURING_AUTO_HEAP_SNAPSHOT"),
  TURING_GIT_BASH_PATH: process.env["TURING_GIT_BASH_PATH"],
  TURING_CONFIG: process.env["TURING_CONFIG"],
  TURING_CONFIG_CONTENT: process.env["TURING_CONFIG_CONTENT"],
  TURING_DISABLE_AUTOUPDATE: truthy("TURING_DISABLE_AUTOUPDATE"),
  TURING_ALWAYS_NOTIFY_UPDATE: truthy("TURING_ALWAYS_NOTIFY_UPDATE"),
  TURING_DISABLE_PRUNE: truthy("TURING_DISABLE_PRUNE"),
  TURING_DISABLE_TERMINAL_TITLE: truthy("TURING_DISABLE_TERMINAL_TITLE"),
  TURING_SHOW_TTFD: truthy("TURING_SHOW_TTFD"),
  TURING_PERMISSION: process.env["TURING_PERMISSION"],
  TURING_DISABLE_DEFAULT_PLUGINS: truthy("TURING_DISABLE_DEFAULT_PLUGINS"),
  TURING_DISABLE_LSP_DOWNLOAD: truthy("TURING_DISABLE_LSP_DOWNLOAD"),
  TURING_ENABLE_EXPERIMENTAL_MODELS: truthy("TURING_ENABLE_EXPERIMENTAL_MODELS"),
  TURING_DISABLE_AUTOCOMPACT: truthy("TURING_DISABLE_AUTOCOMPACT"),
  TURING_DISABLE_MODELS_FETCH: truthy("TURING_DISABLE_MODELS_FETCH"),
  TURING_DISABLE_MOUSE: truthy("TURING_DISABLE_MOUSE"),
  TURING_DISABLE_CLAUDE_CODE,
  TURING_DISABLE_CLAUDE_CODE_PROMPT: TURING_DISABLE_CLAUDE_CODE || truthy("TURING_DISABLE_CLAUDE_CODE_PROMPT"),
  TURING_DISABLE_CLAUDE_CODE_SKILLS,
  TURING_DISABLE_EXTERNAL_SKILLS: TURING_DISABLE_CLAUDE_CODE_SKILLS || truthy("TURING_DISABLE_EXTERNAL_SKILLS"),
  TURING_FAKE_VCS: process.env["TURING_FAKE_VCS"],
  TURING_SERVER_PASSWORD: process.env["TURING_SERVER_PASSWORD"],
  TURING_SERVER_USERNAME: process.env["TURING_SERVER_USERNAME"],
  TURING_ENABLE_QUESTION_TOOL: truthy("TURING_ENABLE_QUESTION_TOOL"),

  // Experimental
  TURING_EXPERIMENTAL,
  TURING_EXPERIMENTAL_FILEWATCHER: Config.boolean("TURING_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  TURING_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("TURING_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  TURING_EXPERIMENTAL_ICON_DISCOVERY: TURING_EXPERIMENTAL || truthy("TURING_EXPERIMENTAL_ICON_DISCOVERY"),
  TURING_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("TURING_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  TURING_ENABLE_EXA: truthy("TURING_ENABLE_EXA") || TURING_EXPERIMENTAL || truthy("TURING_EXPERIMENTAL_EXA"),
  TURING_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("TURING_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  TURING_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("TURING_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  TURING_EXPERIMENTAL_OXFMT: TURING_EXPERIMENTAL || truthy("TURING_EXPERIMENTAL_OXFMT"),
  TURING_EXPERIMENTAL_LSP_TY: truthy("TURING_EXPERIMENTAL_LSP_TY"),
  TURING_EXPERIMENTAL_LSP_TOOL: TURING_EXPERIMENTAL || truthy("TURING_EXPERIMENTAL_LSP_TOOL"),
  TURING_EXPERIMENTAL_PLAN_MODE: TURING_EXPERIMENTAL || truthy("TURING_EXPERIMENTAL_PLAN_MODE"),
  TURING_EXPERIMENTAL_MARKDOWN: !falsy("TURING_EXPERIMENTAL_MARKDOWN"),
  TURING_MODELS_URL: process.env["TURING_MODELS_URL"],
  TURING_MODELS_PATH: process.env["TURING_MODELS_PATH"],
  TURING_DISABLE_EMBEDDED_WEB_UI: truthy("TURING_DISABLE_EMBEDDED_WEB_UI"),
  TURING_DB: process.env["TURING_DB"],
  TURING_DISABLE_CHANNEL_DB: truthy("TURING_DISABLE_CHANNEL_DB"),
  TURING_SKIP_MIGRATIONS: truthy("TURING_SKIP_MIGRATIONS"),
  TURING_STRICT_CONFIG_DEPS: truthy("TURING_STRICT_CONFIG_DEPS"),

  TURING_WORKSPACE_ID: process.env["TURING_WORKSPACE_ID"],
  TURING_EXPERIMENTAL_HTTPAPI: truthy("TURING_EXPERIMENTAL_HTTPAPI"),
  TURING_EXPERIMENTAL_WORKSPACES: TURING_EXPERIMENTAL || truthy("TURING_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get TURING_DISABLE_PROJECT_CONFIG() {
    return truthy("TURING_DISABLE_PROJECT_CONFIG")
  },
  get TURING_TUI_CONFIG() {
    return process.env["TURING_TUI_CONFIG"]
  },
  get TURING_CONFIG_DIR() {
    return process.env["TURING_CONFIG_DIR"]
  },
  get TURING_PURE() {
    return truthy("TURING_PURE")
  },
  get TURING_PLUGIN_META_FILE() {
    return process.env["TURING_PLUGIN_META_FILE"]
  },
  get TURING_CLIENT() {
    return process.env["TURING_CLIENT"] ?? "cli"
  },
}
